"use client";

import { motion } from "framer-motion";
import { Sparkles, Clock, ArrowRight } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import type { CloseAnalysis } from "@/lib/types";

interface NextActionsPanelProps {
  actions: CloseAnalysis["nextActions"];
  headline: string;
  summary: string;
}

export function NextActionsPanel({ actions, headline, summary }: NextActionsPanelProps) {
  return (
    <Card className="h-full ring-glow">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-cc-300" />
            Controller summary
          </CardTitle>
          <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
            Generated by AI · Reviewed by Close Companion
          </span>
        </div>
      </CardHeader>
      <CardContent className="space-y-5">
        <div className="space-y-2">
          <p className="text-base font-medium leading-snug text-white">{headline}</p>
          <p className="text-sm leading-relaxed text-muted-foreground">{summary}</p>
        </div>

        {actions.length > 0 && (
          <div>
            <div className="mb-2 text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
              Suggested next 30 minutes
            </div>
            <ol className="space-y-2">
              {actions.slice(0, 3).map((a, i) => (
                <motion.li
                  key={a.title + i}
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 * i, duration: 0.4 }}
                  className="group flex items-start gap-3 rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 transition-colors hover:border-white/[0.1] hover:bg-white/[0.04]"
                >
                  <span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-md bg-cc-500/10 text-[11px] font-semibold text-cc-300 ring-1 ring-cc-500/20">
                    {i + 1}
                  </span>
                  <div className="min-w-0 flex-1">
                    <div className="text-sm font-medium text-white">{a.title}</div>
                    <div className="mt-0.5 text-xs text-muted-foreground">{a.why}</div>
                    <div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <Clock className="h-3 w-3" />
                        ~{a.estMinutes}m
                      </span>
                      <span>·</span>
                      <span>{a.owner}</span>
                    </div>
                  </div>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="invisible opacity-0 transition-all group-hover:visible group-hover:opacity-100"
                  >
                    Open <ArrowRight className="h-3 w-3" />
                  </Button>
                </motion.li>
              ))}
            </ol>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
